# fly.toml app configuration file generated for transfermarkt-datasets on 2023-06-12T19:15:00+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "transfermarkt-datasets"
primary_region = "mad"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[build]
  image = "registry.fly.io/transfermarkt-datasets:linux-amd64-master"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
