version: 2

sources:
  - name: transfermarkt_scraper
    tables:
      - name: appearances
        meta:
          external_location: >
            read_csv(
              '../data/raw/transfermarkt-scraper/*/appearances.json.gz',
              header=False,
              columns=struct_pack(value := 'VARCHAR'), delim='\1', quote='\0',
              filename=True
            )
      - name: games
        meta:
          external_location: >
            read_csv(
              '../data/raw/transfermarkt-scraper/*/games.json.gz',
              header=False,
              columns=struct_pack(value := 'VARCHAR'), delim='\1', quote='\0',
              filename=True
            )
      - name: players
        meta:
          external_location: >
            read_csv(
              '../data/raw/transfermarkt-scraper/*/players.json.gz',
              header=False,
              columns=struct_pack(value := 'VARCHAR'), delim='\1', quote='\0',
              filename=True
            )
      - name: clubs
        meta:
          external_location: >
            read_csv(
              '../data/raw/transfermarkt-scraper/*/clubs.json.gz',
              header=False,
              columns=struct_pack(value := 'VARCHAR'), delim='\1', quote='\0',
              filename=True
            )
      - name: competitions
        meta:
          external_location: >
            read_csv(
              '../data/competitions.json',
              header=False,
              columns=struct_pack(value := 'VARCHAR'), delim='\1', quote='\0',
              filename=True
            )

      - name: game_lineups
        meta:
          external_location: >
            read_csv(
              '../data/raw/transfermarkt-scraper/*/game_lineups.json.gz',
              header=False,
              columns=struct_pack(value := 'VARCHAR'), delim='\1', quote='\0',
              filename=True
            )
